version: "3.9"
name: "nginx"
services:
  nginx:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf:/etc/nginx/conf.d"
      - "./letsencrypt:/letsencrypt"
    extra_hosts:
      - "mainhost:172.17.0.1"
